# Generated by Django 4.2 on 2024-07-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cartbook',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='userapp.cart'),
            preserve_default=False,
        ),
    ]
